config/routes.rb
BackChannelSummer::Application.routes.draw do
  resources :users
  resources :posts do
    resources :comments
  end
  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/reports', to: 'reports#index'

  root :to => 'posts#index'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                    :integer         not null, primary key
#  email                 :string(255)
#  password              :string(255)
#  password_confirmation :string(255)
#  token                 :string(255)
#  isAdmin               :boolean
#  created_at            :datetime        not null
#  updated_at            :datetime        not null
#

class User < ActiveRecord::Base
  attr_accessible  :email, :password, :password_confirmation, :isAdmin, :token
  before_save :set_attributes
  has_many :posts

  before_save { |user| user.email = email.downcase }

  VALID_EMAIL_REGEXP = /\b[A-Z0-9._%a-z\-]+@(?:[A-Z0-9a-z\-]+\.)+[A-Za-z]{2,4}\z/
  validates :email, presence: true, 
                    format: { with: VALID_EMAIL_REGEXP },
                    uniqueness: { case_sensitive: false }
  validates :password, confirmation: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  validates_associated :posts


  def set_attributes
    self.isAdmin = false if self.isAdmin.nil?
    self.token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_user, only: [:index, :edit, :update]
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to users_url, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully deleted.' }
      format.json { head :no_content }
    end
  end

private
  def admin_user
    @user = self.current_user
    # if current_user is null
    if !@user
      redirect_to signin_path, notice: "Please sign in."
    else
      # if current_user is not admin
      if !@user.isAdmin?
        redirect_to posts_path, notice: "Action not permitted"
      end
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%# passowrd input is now obscured, no need for warning
  <div class="warn">
    <img src="/images/warn.png"></img>
    Passwords are stored as cleartext!<br />Don't enter your private passwords here.<br />We can see them.
  </div>
%>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>
  </div>

  <% if !current_user.nil? && current_user.isAdmin then %>
  <div class="field">
    <%= f.label 'Administrator' %>
    <%= f.check_box :isAdmin %>
  </div>
  <% end %>
  <%= f.submit 'Ok', :class => 'button', :style => 'float:left' %>
  <ul class="actions">
    <li class="button"><%= link_to 'Cancel', users_path %></li>
  </ul>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit">

<h1>Edit user</h1>

<%= render 'form' %>

</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<% if !current_user.nil? && current_user.isAdmin then %>
<ul class="actions"><li class="button"><%= link_to "Create New User", signup_path %></li></ul>
<% end %>

<table>
<thead>
  <tr>
    <th>Email</th>
    <% if !current_user.nil? && current_user.isAdmin then %>
      <th>Password</th>
    <% end %>
    <th>Administrator</th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.email, user %></td>
    <% if !current_user.nil? && current_user.isAdmin then %>
      <td><%= user.password %></td>
    <% end %>
    <td><%= user.isAdmin %></td>
    <% if !current_user.nil? && current_user.isAdmin then %>
      <td>
        <ul class="actions">
          <li class="button"><%= link_to 'Edit', edit_user_path(user) %></li>
          <li class="button"><%= link_to 'Delete', user, confirm: 'Are you sure?', method: :delete %></li>
        </ul>
      </td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>

app/views/users/new.html.erb
<% provide(:title, 'Register') %>

<div class="user-new">

<h1>Create new account</h1>


<%= render 'form' %>

</div>

app/views/users/show.html.erb
<div class="field">
  <label>Email:</label>
  <span class="field-value"><%= @user.email %></span>
</div>

<div class="field">
  <label>Administrator:</label>
  <span class="field-value"><%= @user.isAdmin %></span>
</div>

<div class="field">
  <label>Total posts:</label>
  <span class="field-value"><%= @user.posts.length %></span>
</div>