config/routes.rb
BackChannelSummer::Application.routes.draw do
  resources :users
  resources :posts do
    resources :comments
  end
  
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/reports', to: 'reports#index'

  root :to => 'posts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%
    subtitle = h yield(:title)
    subtitle = ' &bull; ' + subtitle if subtitle.length > 0
  %>
  <title>Back Channel<%=subtitle.html_safe %></title>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <!--[if IE]>
    <link rel="stylesheet" type="text/css" href="/stylesheets/ie-only.css" />
  <![endif]-->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
    $(window).ready(function() {
      setTimeout(function() { 
        $("#notice").animate({ 
            opacity: 'hide', 
          }, 3000); 
      }, 2000 ); 
    });
  </script>
</head>
<body>

<div class="branding"></div>

<div class="content-wrap">

<div class="header">
<div class="tab-menu">
<ul>
<% 
  active = "/#{controller.controller_name}"
  pages = {
    posts_path => ['Home', 'tab-home',false], 
    users_path => ['Manage Users', 'tab-users',true], 
    reports_path => ['Administrator Reports', 'tab-reports',true]
  }
  pages.each do |page|
    if (!page[1][2] || (current_user && current_user.isAdmin?))
      page_classname = page[1][1]
      page_classname += " active" if (page[0] == active && controller.action_name == "index")
%>
  <li class="<%= page_classname %>"><%= link_to page[1][0].html_safe, page[0] %></li>
<%
    end
  end 
%>  
</ul>
</div>

<div class="user-login">
<ul class="actions">
<% if (current_user) %>
  <% classname = 'admin' if current_user.isAdmin? %>
  <li class="<% classname %>">Hello <%= current_user.email %></li>
  <li class="button dark"><%= link_to "Log Out", signout_path %></li>
<% else %>
  <li class="button dark"><%= link_to "Log In", signin_path %></li>
  <li class="button dark"><%= link_to "Register", signup_path %></li>
<% end %>
</ul>
</div>
</div>

<div class="content">

<% if !notice.nil? then %>
<p id="notice"><%= notice %></p>
<% end %>

<%= yield %>

</div>
</div>
</body>
</html>